project_id         = "pulse-analytics-prod-498809"
region             = "us-central1"
topic_name         = "pulse-events"
subscription_name  = "pulse-events-sub"
bq_dataset_id      = "pulse_raw"
bq_table_id        = "events"
bucket_name        = "pulse-analytics-reports"
firestore_location = "nam5"
